### ISSUE TITLE
How to implement code

### ISSUE THREAD

**Issue by mjafartp** [jpnurmi/libserialport.dart#36]
In C# we using Code 

```
Dim sp As SerialPort = New SerialPort("COM15", 9600, Parity.None, 8, StopBits.One)
    sp.Open()
    sp.Write(Convert.ToString(ChrW(12)))
    sp.WriteLine("WELCOME HERE")
    sp.WriteLine(ChrW(13) & "Total Amount:1200")
    sp.Close()
    sp.Dispose()
```

in Flutter Tested Code 
```
final name = SerialPort.availablePorts.last;
    final port = SerialPort(name);
    port.config.baudRate = 9600;
    port.config.bits = 8;
    port.config.stopBits = 1;
    port.config.parity = 0;
    if(!port.isOpen)
      {
        if (!port.openReadWrite()) {
          print(SerialPort.lastError);
        }
      }
  final VISOR_CLEAR = {0x0C};
 port.write(Uint8List.fromList("WELCOME HERE".codeUnits));
```

it's not working in flutter

**Comment by jpnurmi** [comment]
Hi, try the workaround proposed at https://github.com/jpnurmi/libserialport.dart/issues/24#issuecomment-812918216.

**Comment by mjafartp** [comment]
Hi,
tried still receive incorrect data

**Comment by jpnurmi** [comment]
Do you have a possibility to try with the [libserialport](https://sigrok.org/wiki/Libserialport) C-library?

**Comment by jpnurmi** [comment]
They have some simple examples. For example, [send_receive.c](https://github.com/sigrokproject/libserialport/blob/master/examples/send_receive.c) could be a good starting point for a minimal test case. You know, just to see if the underlying C-library handles it correctly.

**Comment by mjafartp** [comment]
Yes,
it's working good on this C-library

**Comment by jpnurmi** [comment]
Great! Thank you for testing it - much appreciated. Then we can conclude that the problem is with the FFI bindings. :smile:

**Comment by mjafartp** [comment]
Any Update on this issue?

**Comment by jpnurmi** [comment]
I can't think of any better way for me to verify this than patching the libserialport C-library to be able to inspect the call sequence. It's a bit of effort and I've been pretty busy with other things recently, sorry.

**Comment by jpnurmi** [comment]
Is it just a matter of opening the port first, and then applying the config?

If I run the following test app:
```dart
final port = SerialPort('/dev/tnt0');
port.config.baudRate = 9600;
port.openRead();
```
With `LIBSERIALPORT_DEBUG=1 environment variable, the output is:
```
sp: sp_get_port_by_name(/dev/tnt0, 0x56064a166040) called.
sp: Building structure for port /dev/tnt0.
sp: get_port_details returning SP_OK.
sp: sp_get_port_by_name returning SP_OK.
sp: sp_new_config(0x56064a166098) called.
sp: sp_new_config returning SP_OK.
sp: sp_get_config(0x56064a19cc80, 0x56064a3cc000) called.
sp: sp_get_config returning SP_ERR_ARG: Port not open.
sp: sp_last_error_message() called.
sp: sp_last_error_message returning Invalid argument.
sp: sp_free_error_message(Invalid argument) called.
sp: sp_free_error_message returning.
sp: sp_last_error_code() called.
sp: sp_last_error_code returning 22.
sp: sp_last_error_message() called.
sp: sp_last_error_message returning Invalid argument.
sp: sp_free_error_message(Invalid argument) called.
sp: sp_free_error_message returning.
sp: sp_last_error_code() called.
sp: sp_last_error_code returning 22.
Unhandled exception:
SerialPortError: Invalid argument, errno = 22
#0      Util.call (package:libserialport/src/util.dart:39:7)
#1      _SerialPortImpl.config (package:libserialport/src/port.dart:335:12)
#2      main (file:///home/jpnurmi/Projects/libserialport.dart/example/example.dart:7:6)
#3      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

However, if I change the order:
```dart
final port = SerialPort('/dev/tnt0');
port.openRead();
port.config.baudRate = 9600;
```
Then the output is:
```
sp: sp_get_port_by_name(/dev/tnt0, 0x55650c0960a0) called.
sp: Building structure for port /dev/tnt0.
sp: get_port_details returning SP_OK.
sp: sp_get_port_by_name returning SP_OK.
sp: sp_open(0x55650c0cca50, 0x1) called.
sp: Opening port /dev/tnt0.
sp: get_config(0x55650c0cca50, 0x7f0e8e50d480, 0x7f0e8e50d450) called.
sp: Getting configuration for port /dev/tnt0.
sp: get_flow(9, 0x7f0e8e50d480) called.
sp: Getting advanced flow control.
sp: sp_last_error_message() called.
sp: sp_last_error_message returning Invalid argument.
sp: get_flow returning SP_ERR_FAIL: Getting termiox failed: Invalid argument.
sp: sp_free_error_message(Invalid argument) called.
sp: sp_free_error_message returning.
sp: get_config returning SP_OK.
sp: set_config(0x55650c0cca50, 0x7f0e8e50d480, 0x7f0e8e50d450) called.
sp: Setting configuration for port /dev/tnt0.
sp: set_config returning SP_OK.
sp: sp_open returning SP_OK.
sp: sp_new_config(0x55650c096068) called.
sp: sp_new_config returning SP_OK.
sp: sp_get_config(0x55650c0cca50, 0x55650c3f4720) called.
sp: get_config(0x55650c0cca50, 0x7f0e8e50d460, 0x55650c3f4720) called.
sp: Getting configuration for port /dev/tnt0.
sp: get_flow(9, 0x7f0e8e50d460) called.
sp: Getting advanced flow control.
sp: sp_last_error_message() called.
sp: sp_last_error_message returning Invalid argument.
sp: get_flow returning SP_ERR_FAIL: Getting termiox failed: Invalid argument.
sp: sp_free_error_message(Invalid argument) called.
sp: sp_free_error_message returning.
sp: get_config returning SP_OK.
sp: sp_get_config returning SP_OK.
sp: sp_set_config_baudrate(0x55650c3f4720, 9600) called.
sp: sp_set_config_baudrate returning SP_OK.
```

**Comment by Cresso** [comment]
> In C# we using Code
> 
> ```
> Dim sp As SerialPort = New SerialPort("COM15", 9600, Parity.None, 8, StopBits.One)
>     sp.Open()
>     sp.Write(Convert.ToString(ChrW(12)))
>     sp.WriteLine("WELCOME HERE")
>     sp.WriteLine(ChrW(13) & "Total Amount:1200")
>     sp.Close()
>     sp.Dispose()
> ```
> 
> in Flutter Tested Code
> 
> ```
> final name = SerialPort.availablePorts.last;
>     final port = SerialPort(name);
>     port.config.baudRate = 9600;
>     port.config.bits = 8;
>     port.config.stopBits = 1;
>     port.config.parity = 0;
>     if(!port.isOpen)
>       {
>         if (!port.openReadWrite()) {
>           print(SerialPort.lastError);
>         }
>       }
>   final VISOR_CLEAR = {0x0C};
>  port.write(Uint8List.fromList("WELCOME HERE".codeUnits));
> ```
> 
> it's not working in flutter

I've the same issue.
need help.
`print(ports);
                       final port = SerialPort(ports.last);

                        port.config.baudRate = 115200;
                        port.config.bits = 8;
                        port.config.stopBits = 1;
                        port.config.parity = 0;

                        if(!port.isOpen)
                        {
                          if (!port.openReadWrite()) {
                            print(SerialPort.lastError);
                          }
                        }
                        
                        port.write(Uint8List.fromList("WELCOME HERE".codeUnits));
                        final reader = SerialPortReader(port);
                        reader.stream.listen((data) {
                          print('received: $data');
                        });`

I have error  **Operation not permitted, errno = 1**
