### ISSUE TITLE
Windows -- SerialPortError access denied error=5

### ISSUE THREAD

**Issue by EdvaldoMartins** [jpnurmi/libserialport.dart#49]
Hello team, I'm having trouble making the connection.

```
SerialPortError access denied error = 5
```
I'm using flutter for desktop, do I need to add some special permission to be able to run on windows?

Thanks

**Comment by realrk95** [comment]
Share some code. I think you're trying to open the com port again and again.

**Comment by akashfibonalabs** [comment]
SerialPortError: Access is denied., errno = 5
Unhandled Exception: SerialPortError: The operation completed successfully., errno = 0


same facing issue not able to read data from windows

**Comment by Sounean** [comment]
These ports may have already been opened.
You can first try opening the port through software like "SSCOM", and based on their error message, see if it has already been opened and occupied elsewhere.

**Comment by eximius313** [comment]
Here is the stack trace:
```
SerialPortError: Access is denied., errno = 5
#0      Util.call (package:libserialport/src/util.dart:40:7)
util.dart:40
#1      _SerialPortImpl.config (package:libserialport/src/port.dart:335:12)
port.dart:335
#2      SerialClient.initialize (package:test/src/serial_client.dart:49:16)
serial_client.dart:49
```

and code:
```dart
import 'dart:async';
import 'dart:typed_data';

import 'package:libserialport/libserialport.dart';

class SerialClient {
  static const _baudRate = 9600;
  static const _bits = 8;
  static const _parity = SerialPortParity.none;
  static const _stopBits = 1;
  static const _flowControl = SerialPortFlowControl.rtsCts;

  final String _portName; // 'COM3'

  SerialPort? _port;
  Stream<Uint8List>? _stream;
  SerialPortReader? _reader;

  SerialClient(this._portName);

  Future<bool> initialize() async {
    try {
      _port = SerialPort(_portName);

      if (!_port!.openReadWrite()) {
        final error = SerialPort.lastError;
        print('Can not open serial port: ${_port?.name}. Error: ${error?.message} (ErrorCode: ${error?.errorCode})');
        _port!.config.dispose();
        return false;
      }

      // https://github.com/jpnurmi/libserialport.dart/issues/24
      final config = SerialPortConfig()
        ..baudRate = _baudRate
        ..bits = _bits
        ..parity = _parity
        ..stopBits = _stopBits
        ..setFlowControl(_flowControl);
      _port!.config = config;

      // config.dispose(); //https://github.com/jpnurmi/flutter_libserialport/issues/148
    
      _reader = SerialPortReader(_port!);
      _stream = _reader!.stream.asBroadcastStream().handleError((final Object error) {
        print('SERIAL ERROR $error');
      });
    
    } catch (error, stackTrace) {
      print('Error while initializing port $error');
    }
    return true;
  }
}
```
