### ISSUE TITLE
[ERROR:flutter/runtime/dart_isolate.cc(1098)] Unhandled exception:

### ISSUE THREAD

**Issue by omidFdisk** [jpnurmi/libserialport.dart#58]
I have same issue:
[ERROR:flutter/runtime/dart_isolate.cc(1098)] Unhandled exception:
Invalid argument(s): length must be in the range [0, 4611686018427387903].
#0      _checkExternalTypedDataLength (dart:ffi-patch/ffi_patch.dart:60:5)
#1      Uint8Pointer.asTypedList (dart:ffi-patch/ffi_patch.dart:620:5)
#2      Util.read (package:libserialport/src/util.dart:47:40)
#3      _SerialPortReaderImpl._waitRead (package:libserialport/src/reader.dart:145:27)
#4      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:300:17)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
please help

**Comment by springeye** [comment]
me to
